rules:
  checkSemanticVersion:
    description: "Validates semantic versioning"
    given: $.info
    severity: error
    then:
      - field: version
        function: pattern
        functionOptions:
          match: "^[0-9]\.[0-9]\.[0-9]\.[0-9]$"
